// =============================================================================
// PeopleOS PH - Export Generators
// =============================================================================
// Generates export content from payroll data with immutable snapshots
// =============================================================================

import { createHash } from "crypto";
import type {
  ExportResult,
  PayrollRegisterRow,
  BankDisbursementRow,
  SSSContributionRow,
  PhilHealthContributionRow,
  PagIBIGContributionRow,
  DetailedPayrollRow,
  AttendanceDetailRow,
  ExportMetadata,
} from "./types";
import type { ExportType } from "@/app/generated/prisma";

/**
 * Generate SHA-256 hash of content
 */
export function generateContentHash(content: Buffer): string {
  return createHash("sha256").update(content).digest("hex");
}

/**
 * Convert array of objects to CSV string
 */
function arrayToCSV<T>(
  data: T[],
  headers: { key: keyof T; label: string }[]
): string {
  const headerRow = headers.map((h) => `"${h.label}"`).join(",");
  const dataRows = data.map((row) =>
    headers
      .map((h) => {
        const value = row[h.key];
        if (typeof value === "number") {
          return value.toFixed(2);
        }
        if (value === null || value === undefined) {
          return "";
        }
        // Escape quotes and wrap in quotes
        return `"${String(value).replace(/"/g, '""')}"`;
      })
      .join(",")
  );
  return [headerRow, ...dataRows].join("\n");
}

/**
 * Generate payroll register CSV
 */
export function generatePayrollRegisterCSV(
  rows: PayrollRegisterRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof PayrollRegisterRow; label: string }[] = [
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "department", label: "Department" },
    { key: "position", label: "Position" },
    { key: "wageType", label: "Wage Type" },
    { key: "baseRate", label: "Base Rate" },
    { key: "basicPay", label: "Basic Pay" },
    { key: "overtime", label: "Overtime" },
    { key: "nightDiff", label: "Night Diff" },
    { key: "holidayPay", label: "Holiday Pay" },
    { key: "restDayPay", label: "Rest Day Pay" },
    { key: "allowances", label: "Allowances" },
    { key: "reimbursements", label: "Reimbursements" },
    { key: "adjustmentsAdd", label: "Adjustments (+)" },
    { key: "grossPay", label: "Gross Pay" },
    { key: "lateDeduction", label: "Late Deduction" },
    { key: "undertimeDeduction", label: "Undertime Deduction" },
    { key: "absentDeduction", label: "Absent Deduction" },
    { key: "sssEe", label: "SSS" },
    { key: "philhealthEe", label: "PhilHealth" },
    { key: "pagibigEe", label: "Pag-IBIG" },
    { key: "withholdingTax", label: "Withholding Tax" },
    { key: "cashAdvanceDeduction", label: "Cash Advance" },
    { key: "loanDeduction", label: "Loan Deduction" },
    { key: "adjustmentsDeduct", label: "Adjustments (-)" },
    { key: "otherDeductions", label: "Other Deductions" },
    { key: "totalDeductions", label: "Total Deductions" },
    { key: "netPay", label: "Net Pay" },
    { key: "bankName", label: "Bank" },
    { key: "bankAccountNumber", label: "Account Number" },
  ];

  // Add metadata header
  const metadataLines = [
    `"PeopleOS PH - Payroll Register"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    `"Total Net Pay:","${(metadata.totalAmount || 0).toFixed(2)}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  const totalAmount = rows.reduce((sum, r) => sum + r.netPay, 0);

  return {
    success: true,
    exportType: "PAYROLL_REGISTER" as ExportType,
    fileName: `payroll-register-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    totalAmount,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      employeeCount: rows.length,
      totalGrossPay: rows.reduce((sum, r) => sum + r.grossPay, 0),
      totalDeductions: rows.reduce((sum, r) => sum + r.totalDeductions, 0),
      totalNetPay: totalAmount,
      rowHashes: rows.map((r) =>
        createHash("md5")
          .update(`${r.employeeNumber}-${r.netPay}`)
          .digest("hex")
          .substring(0, 8)
      ),
    },
  };
}

/**
 * Generate bank disbursement CSV
 */
export function generateBankDisbursementCSV(
  rows: BankDisbursementRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof BankDisbursementRow; label: string }[] = [
    { key: "sequenceNumber", label: "Seq No." },
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "bankCode", label: "Bank Code" },
    { key: "bankName", label: "Bank Name" },
    { key: "accountNumber", label: "Account Number" },
    { key: "accountType", label: "Account Type" },
    { key: "amount", label: "Amount" },
    { key: "remarks", label: "Remarks" },
  ];

  const metadataLines = [
    `"PeopleOS PH - Bank Disbursement File"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    `"Total Amount:","${(metadata.totalAmount || 0).toFixed(2)}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  const totalAmount = rows.reduce((sum, r) => sum + r.amount, 0);

  return {
    success: true,
    exportType: "BANK_DISBURSEMENT" as ExportType,
    fileName: `bank-disbursement-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    totalAmount,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      recordCount: rows.length,
      totalAmount,
      bankCodes: [...new Set(rows.map((r) => r.bankCode))],
    },
  };
}

/**
 * Generate SSS contributions CSV
 */
export function generateSSSContributionsCSV(
  rows: SSSContributionRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof SSSContributionRow; label: string }[] = [
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "sssNumber", label: "SSS Number" },
    { key: "monthlyBasicSalary", label: "Monthly Basic Salary" },
    { key: "employeeShare", label: "Employee Share" },
    { key: "employerShare", label: "Employer Share" },
    { key: "ecContribution", label: "EC Contribution" },
    { key: "totalContribution", label: "Total Contribution" },
  ];

  const metadataLines = [
    `"PeopleOS PH - SSS Contributions"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  const totalAmount = rows.reduce((sum, r) => sum + r.totalContribution, 0);

  return {
    success: true,
    exportType: "SSS_CONTRIBUTIONS" as ExportType,
    fileName: `sss-contributions-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    totalAmount,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      recordCount: rows.length,
      totalEmployeeShare: rows.reduce((sum, r) => sum + r.employeeShare, 0),
      totalEmployerShare: rows.reduce((sum, r) => sum + r.employerShare, 0),
      totalContribution: totalAmount,
    },
  };
}

/**
 * Generate PhilHealth contributions CSV
 */
export function generatePhilHealthContributionsCSV(
  rows: PhilHealthContributionRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof PhilHealthContributionRow; label: string }[] = [
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "philhealthNumber", label: "PhilHealth Number" },
    { key: "monthlyBasicSalary", label: "Monthly Basic Salary" },
    { key: "employeeShare", label: "Employee Share" },
    { key: "employerShare", label: "Employer Share" },
    { key: "totalContribution", label: "Total Contribution" },
  ];

  const metadataLines = [
    `"PeopleOS PH - PhilHealth Contributions"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  const totalAmount = rows.reduce((sum, r) => sum + r.totalContribution, 0);

  return {
    success: true,
    exportType: "PHILHEALTH_CONTRIBUTIONS" as ExportType,
    fileName: `philhealth-contributions-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    totalAmount,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      recordCount: rows.length,
      totalEmployeeShare: rows.reduce((sum, r) => sum + r.employeeShare, 0),
      totalEmployerShare: rows.reduce((sum, r) => sum + r.employerShare, 0),
      totalContribution: totalAmount,
    },
  };
}

/**
 * Generate Pag-IBIG contributions CSV
 */
export function generatePagIBIGContributionsCSV(
  rows: PagIBIGContributionRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof PagIBIGContributionRow; label: string }[] = [
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "pagibigNumber", label: "Pag-IBIG Number" },
    { key: "monthlyBasicSalary", label: "Monthly Basic Salary" },
    { key: "employeeShare", label: "Employee Share" },
    { key: "employerShare", label: "Employer Share" },
    { key: "totalContribution", label: "Total Contribution" },
  ];

  const metadataLines = [
    `"PeopleOS PH - Pag-IBIG Contributions"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  const totalAmount = rows.reduce((sum, r) => sum + r.totalContribution, 0);

  return {
    success: true,
    exportType: "PAGIBIG_CONTRIBUTIONS" as ExportType,
    fileName: `pagibig-contributions-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    totalAmount,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      recordCount: rows.length,
      totalEmployeeShare: rows.reduce((sum, r) => sum + r.employeeShare, 0),
      totalEmployerShare: rows.reduce((sum, r) => sum + r.employerShare, 0),
      totalContribution: totalAmount,
    },
  };
}

/**
 * Generate detailed payroll register CSV with all breakdowns
 */
export function generateDetailedPayrollCSV(
  rows: DetailedPayrollRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof DetailedPayrollRow; label: string }[] = [
    // Employee Info
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "department", label: "Department" },
    { key: "position", label: "Position" },
    { key: "hiringEntity", label: "Hiring Entity" },
    { key: "wageType", label: "Wage Type" },
    { key: "baseRate", label: "Base Rate" },

    // Attendance Summary
    { key: "workingDays", label: "Working Days" },
    { key: "daysWorked", label: "Days Worked" },
    { key: "daysAbsent", label: "Days Absent" },
    { key: "regularHours", label: "Regular Hours" },
    { key: "lateMinutes", label: "Late (mins)" },
    { key: "undertimeMinutes", label: "Undertime (mins)" },
    { key: "overtimeHours", label: "OT Hours" },
    { key: "nightDiffHours", label: "Night Diff Hours" },

    // Holiday Work
    { key: "regularHolidayDays", label: "Regular Holiday Days" },
    { key: "regularHolidayPay", label: "Regular Holiday Pay" },
    { key: "specialHolidayDays", label: "Special Holiday Days" },
    { key: "specialHolidayPay", label: "Special Holiday Pay" },

    // Rest Day Work
    { key: "restDayDays", label: "Rest Day Days" },
    { key: "restDayPay", label: "Rest Day Pay" },

    // Earnings Breakdown
    { key: "basicPay", label: "Basic Pay" },
    { key: "overtimePay", label: "Overtime Pay" },
    { key: "nightDiffPay", label: "Night Diff Pay" },
    { key: "holidayPay", label: "Holiday Pay (Total)" },
    { key: "allowances", label: "Allowances" },
    { key: "reimbursements", label: "Reimbursements" },
    { key: "adjustmentsAdd", label: "Adjustments (+)" },
    { key: "grossPay", label: "Gross Pay" },

    // Deductions Breakdown
    { key: "lateDeduction", label: "Late Deduction" },
    { key: "undertimeDeduction", label: "Undertime Deduction" },
    { key: "absentDeduction", label: "Absent Deduction" },
    { key: "sssEe", label: "SSS (EE)" },
    { key: "sssEr", label: "SSS (ER)" },
    { key: "philhealthEe", label: "PhilHealth (EE)" },
    { key: "philhealthEr", label: "PhilHealth (ER)" },
    { key: "pagibigEe", label: "Pag-IBIG (EE)" },
    { key: "pagibigEr", label: "Pag-IBIG (ER)" },
    { key: "withholdingTax", label: "Withholding Tax" },
    { key: "cashAdvanceDeduction", label: "Cash Advance" },
    { key: "loanDeduction", label: "Loan Deduction" },
    { key: "adjustmentsDeduct", label: "Adjustments (-)" },
    { key: "otherDeductions", label: "Other Deductions" },
    { key: "totalDeductions", label: "Total Deductions" },

    // Net Pay
    { key: "netPay", label: "Net Pay" },

    // Bank Info
    { key: "bankName", label: "Bank" },
    { key: "bankAccountNumber", label: "Account Number" },
  ];

  const metadataLines = [
    `"PeopleOS PH - Detailed Payroll Register"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    `"Total Net Pay:","${(metadata.totalAmount || 0).toFixed(2)}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  const totalAmount = rows.reduce((sum, r) => sum + r.netPay, 0);

  return {
    success: true,
    exportType: "PAYROLL_REGISTER" as ExportType,
    fileName: `detailed-payroll-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    totalAmount,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      employeeCount: rows.length,
      totalGrossPay: rows.reduce((sum, r) => sum + r.grossPay, 0),
      totalDeductions: rows.reduce((sum, r) => sum + r.totalDeductions, 0),
      totalNetPay: totalAmount,
      totalRegularHolidayPay: rows.reduce((sum, r) => sum + r.regularHolidayPay, 0),
      totalSpecialHolidayPay: rows.reduce((sum, r) => sum + r.specialHolidayPay, 0),
      totalRestDayPay: rows.reduce((sum, r) => sum + r.restDayPay, 0),
      totalOvertimePay: rows.reduce((sum, r) => sum + r.overtimePay, 0),
      totalNightDiffPay: rows.reduce((sum, r) => sum + r.nightDiffPay, 0),
    },
  };
}

/**
 * Generate attendance detail CSV for a pay period
 */
export function generateAttendanceDetailCSV(
  rows: AttendanceDetailRow[],
  metadata: ExportMetadata
): ExportResult {
  const headers: { key: keyof AttendanceDetailRow; label: string }[] = [
    { key: "employeeNumber", label: "Employee No." },
    { key: "employeeName", label: "Employee Name" },
    { key: "date", label: "Date" },
    { key: "dayOfWeek", label: "Day" },
    { key: "dayType", label: "Day Type" },
    { key: "holidayName", label: "Holiday Name" },
    { key: "scheduledIn", label: "Scheduled In" },
    { key: "scheduledOut", label: "Scheduled Out" },
    { key: "actualIn", label: "Actual In" },
    { key: "actualOut", label: "Actual Out" },
    { key: "hoursWorked", label: "Hours Worked" },
    { key: "lateMinutes", label: "Late (mins)" },
    { key: "undertimeMinutes", label: "Undertime (mins)" },
    { key: "overtimeMinutes", label: "OT (mins)" },
    { key: "nightDiffMinutes", label: "Night Diff (mins)" },
    { key: "status", label: "Status" },
    { key: "remarks", label: "Remarks" },
  ];

  const metadataLines = [
    `"PeopleOS PH - Attendance Detail Report"`,
    `"Company:","${metadata.companyName}"`,
    `"Pay Period:","${metadata.payPeriodCode}"`,
    `"Generated:","${metadata.generatedAt.toISOString()}"`,
    `"Generated By:","${metadata.generatedBy}"`,
    `"Record Count:","${metadata.recordCount}"`,
    ``,
  ];

  const csvContent = arrayToCSV(rows, headers);
  const fullContent = [...metadataLines, csvContent].join("\n");
  const content = Buffer.from(fullContent, "utf-8");
  const contentHash = generateContentHash(content);

  // Count unique employees
  const uniqueEmployees = new Set(rows.map((r) => r.employeeNumber)).size;

  return {
    success: true,
    exportType: "PAYROLL_REGISTER" as ExportType, // Using PAYROLL_REGISTER as it's related
    fileName: `attendance-detail-${metadata.payPeriodCode}-${Date.now()}.csv`,
    mimeType: "text/csv",
    content,
    contentHash,
    recordCount: rows.length,
    dataSnapshot: {
      payrollRunId: metadata.payrollRunId,
      payPeriodCode: metadata.payPeriodCode,
      employeeCount: uniqueEmployees,
      totalRecords: rows.length,
      totalHoursWorked: rows.reduce((sum, r) => sum + r.hoursWorked, 0),
      totalLateMinutes: rows.reduce((sum, r) => sum + r.lateMinutes, 0),
      totalUndertimeMinutes: rows.reduce((sum, r) => sum + r.undertimeMinutes, 0),
      totalOvertimeMinutes: rows.reduce((sum, r) => sum + r.overtimeMinutes, 0),
      totalNightDiffMinutes: rows.reduce((sum, r) => sum + r.nightDiffMinutes, 0),
    },
  };
}
